name    'abjorshammar-accounts'
version '0.1.5'
source 'git@github.com:abjorshammar/puppet-accounts.git'
author 'abjorshammar'
license 'Apache License, Version 2.0'
summary 'Manage local accounts'
description 'Manages local accounts and SSH keys'
project_page 'https://github.com/abjorshammar/puppet-accounts'

dependency 'puppetlabs/stdlib', '>=4.0.0'
